src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.API/Validations/User/CompanyValidator.cs
src/PerfectBreakfast.Application/Interfaces/ICompanyService.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Request/CompanyRequest.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Request/UpdateCompanyRequest.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Response/CompanyResponse.cs
src/PerfectBreakfast.Application/PerfectBreakfast.Application.csproj
src/PerfectBreakfast.Application/Repositories/ICompanyRepository.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/UserService.cs
src/PerfectBreakfast.Infrastructure/Repositories/CompanyRepository.cs

#3 feat/CRUD_Company

---

src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.Application/Interfaces/ICompanyService.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs

Get paging company and delete not real

#3 feat/Get_paging_company

---

src/PerfectBreakfast.API/Controllers/V1/CategoryController.cs
src/PerfectBreakfast.API/Validations/Category/CategoryValidator.cs
src/PerfectBreakfast.Application/Interfaces/ICategoryService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Request/CreateCategoryRequest.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Request/UpdateCategoryRequest.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Response/CategoryResponse.cs
src/PerfectBreakfast.Application/Repositories/ICategoryRepository.cs
src/PerfectBreakfast.Application/Services/CategoryService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Repositories/CategoryRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

#10 Crud_Category

---

src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Validations/Food/FoodValidator.cs
src/PerfectBreakfast.Application/Interfaces/IFoodService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/CreateFoodRequestModels.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/UpdateFoodRequestModels.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/FoodResponse.cs
src/PerfectBreakfast.Application/Repositories/IFoodRepository.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Mappers/MapsterConfig.cs
src/PerfectBreakfast.Infrastructure/Repositories/FoodRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

Crud  food (issue #13)

---

src/PerfectBreakfast.API/Controllers/V1/MenuComtroller.cs
src/PerfectBreakfast.API/Controllers/V1/PaymentMethodController.cs
src/PerfectBreakfast.API/Validations/Company/CompanyValidator.cs
src/PerfectBreakfast.API/Validations/Menu/MenuValidator.cs
src/PerfectBreakfast.API/Validations/PaymentMethod/PaymentMethodValidator.cs
src/PerfectBreakfast.Application/Interfaces/IMenuService.cs
src/PerfectBreakfast.Application/Interfaces/IPaymentMethodService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/MenuModels/Request/MenuRequest.cs
src/PerfectBreakfast.Application/Models/MenuModels/Request/UpdateMenuRequest.cs
src/PerfectBreakfast.Application/Models/MenuModels/Response/MenuResponse.cs
src/PerfectBreakfast.Application/Models/PaymentMethodModels/Request/PaymentMethodRequest.cs
src/PerfectBreakfast.Application/Models/PaymentMethodModels/Response/PaymentMethodResponse.cs
src/PerfectBreakfast.Application/Repositories/IMenuRepository.cs
src/PerfectBreakfast.Application/Repositories/IPaymentMethodRepository.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Application/Services/PaymentMethodService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Repositories/MenuRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/PaymentMethodRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

Feat/crud  menu & payment method and finish delete company

Feat/crud  menu & payment method

---

src/PerfectBreakfast.Application/Models/CategoryModels/Request/CreateCategoryRequest.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Request/UpdateCategoryRequest.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Response/CategoryResponse.cs
src/PerfectBreakfast.Application/Models/DeliveryUnitModels/Request/CreateDeliveryUnitRequest.cs
src/PerfectBreakfast.Application/Models/DeliveryUnitModels/Request/UpdateDeliveryUnitRequest.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/CreateFoodRequestModels.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/UpdateFoodRequestModels.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/FoodResponse.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Request/CreateManagementUnitRequest.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Request/UpdateManagementUnitRequest.cs
src/PerfectBreakfast.Application/Models/RoleModels/Request/CreatRoleRequest.cs
src/PerfectBreakfast.Application/Models/RoleModels/Request/UpdateRolerequest.cs

#31 edit create food

---

src/PerfectBreakfast.API/Controllers/V1/CategoryController.cs
src/PerfectBreakfast.Application/Interfaces/ICategoryService.cs
src/PerfectBreakfast.Application/Services/CategoryService.cs
src/PerfectBreakfast.Domain/Entities/Combo.cs
src/PerfectBreakfast.Infrastructure/Migrations/20240109161826_NewMigration.Designer.cs
src/PerfectBreakfast.Infrastructure/Migrations/20240109161826_NewMigration.cs

#38 fix name category

---

src/PerfectBreakfast.Application/Models/DeliveryUnitModels/Response/DeliveryUnitResponseModel.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitResponseModel.cs

Add id deliveryUnit-ManagerUnits

Add id deliveryUnit-ManagerUnits

---

src/PerfectBreakfast.API/Controllers/V1/ComboController.cs
src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/MenuComtroller.cs
src/PerfectBreakfast.API/Validations/DailyOrder/UpdateDailyOrderValidatorcs.cs
src/PerfectBreakfast.Application/Interfaces/ICompanyService.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Request/CompanyRequest.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Request/UpdateCompanyRequest.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Response/CompanyResponse.cs
src/PerfectBreakfast.Application/Models/DaliyOrder/Request/UpdateDailyOrderRequest.cs
src/PerfectBreakfast.Application/Models/MenuModels/Response/ComboAndFoodResponse.cs
src/PerfectBreakfast.Application/Models/MenuModels/Response/MenuResponse.cs
src/PerfectBreakfast.Application/Services/ComboService.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

Fix add not find id to menu and combo 
xoa create menu controller 
Fix gom foodResponse và comboResponse thành 1 model.
Đặt lại tên 
Create xong phải trả về 200 
Fix all update function 
Company thêm truờng mới

#41 fix-somthings

---

src/PerfectBreakfast.API/Controllers/V1/PaymentController.cs
src/PerfectBreakfast.API/DependencyInjection.cs
src/PerfectBreakfast.API/Program.cs
src/PerfectBreakfast.API/appsettings.json
src/PerfectBreakfast.Application/Commons/AppConfiguration.cs
src/PerfectBreakfast.Application/Commons/PayOSSettings.cs
src/PerfectBreakfast.Application/Interfaces/IPayOSService.cs
src/PerfectBreakfast.Application/Models/PayOSModels/PayOSRequest/ReturnPayOSRequest.cs
src/PerfectBreakfast.Application/Models/PaymentModels/Respone/PaymentRespone.cs
src/PerfectBreakfast.Application/PerfectBreakfast.Application.csproj
src/PerfectBreakfast.Domain/Entities/Order.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/FluentAPIs/OrderConfig.cs
src/PerfectBreakfast.Infrastructure/Migrations/20240111065212_OrderCode.Designer.cs
src/PerfectBreakfast.Infrastructure/Migrations/20240111065212_OrderCode.cs
src/PerfectBreakfast.Infrastructure/Payments/PayOSService.cs

PayOSAPICreateLink

---

src/PerfectBreakfast.API/Controllers/V1/DeliveryUnitController.cs
src/PerfectBreakfast.API/Controllers/V1/ManagementUnitController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierCommissionRateController.cs
src/PerfectBreakfast.API/Validations/SupplierCommissionRate/SupplierCommissionRateValidator.cs
src/PerfectBreakfast.Application/Interfaces/IDeliveryUnitService.cs
src/PerfectBreakfast.Application/Interfaces/IManagementUnitService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierCommissionRateService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/DeliveryUnitModels/Response/DeliveryUnitResponseModel.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitResponseModel.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Request/CreateSupplierCommissionRateRequest.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Request/UpdateSupplierCommissionRateRequest.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Respone/SupplierCommissionRateRespone.cs
src/PerfectBreakfast.Application/Repositories/ISupplierCommissionRateRepository.cs
src/PerfectBreakfast.Application/Services/DeliveryUnitService.cs
src/PerfectBreakfast.Application/Services/ManagementUnitService.cs
src/PerfectBreakfast.Application/Services/SupplierCommissionRateService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierCommissionRateRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

#50crud SupplierCommissionRate

#50crud SupplierCommissionRate 

---

src/PerfectBreakfast.API/PerfectBreakfast.API.csproj
src/PerfectBreakfast.API/Program.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IMailService.cs
src/PerfectBreakfast.Application/Models/DaliyOrder/Response/DailyOrderResponse.cs
src/PerfectBreakfast.Application/Models/MailModels/MailDataViewModel.cs
src/PerfectBreakfast.Application/PerfectBreakfast.Application.csproj
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Domain/Entities/DailyOrder.cs
src/PerfectBreakfast.Infrastructure/MailServices/MailService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

#55 implement Hangfire

---

src/PerfectBreakfast.API/Controllers/V1/SupplierCommissionRateController.cs
src/PerfectBreakfast.API/Validations/SupplierCommissionRate/SupplierCommissionRateValidator.cs
src/PerfectBreakfast.Application/Commons/OperationResult.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierCommissionRateService.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Request/CreateSupplierCommissionRateRequest.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Request/CreateSupplierMoreFood.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Request/UpdateSupplierCommissionRateRequest.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Respone/SupplierMoreFoodRespone.cs
src/PerfectBreakfast.Application/Repositories/ISupplierCommissionRateRepository.cs
src/PerfectBreakfast.Application/Services/SupplierCommissionRateService.cs
src/PerfectBreakfast.Domain/Entities/SupplierCommissionRate.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierCommissionRateRepository.cs

đăng ký ncc với nhiều food cùng lúc

đăng ký ncc với nhiều food cùng lúc

---

src/PerfectBreakfast.API/Controllers/V1/CategoryController.cs
src/PerfectBreakfast.Application/Interfaces/ICategoryService.cs
src/PerfectBreakfast.Application/Interfaces/IFoodService.cs
src/PerfectBreakfast.Application/Models/CategoryModels/Response/CategoryDetailFood.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/FoodResponeCategory.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/FoodResponse.cs
src/PerfectBreakfast.Application/Services/CategoryService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs

get CategoeyDetail

---

src/PerfectBreakfast.API/Validations/Menu/MenuValidator.cs
src/PerfectBreakfast.Application/Models/DaliyOrder/Response/DailyOrderResponseExcel.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/ComboService.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

Update order statistics background  job

Update order statistics background  job

---

src/PerfectBreakfast.API/Controllers/V1/SupplierController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplyAssigmentController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplyAssigmentService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitDTO.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitResponseModel.cs
src/PerfectBreakfast.Application/Models/SupplierModels/Response/SupplierDTO.cs
src/PerfectBreakfast.Application/Models/SupplierModels/Response/SupplierResponse.cs
src/PerfectBreakfast.Application/Models/SupplyAssigmentModels/Request/CreateSupplyAssigment.cs
src/PerfectBreakfast.Application/Models/SupplyAssigmentModels/Request/UpdateSupplyAssigment.cs
src/PerfectBreakfast.Application/Models/SupplyAssigmentModels/Response/SupplyAssigmentResponse.cs
src/PerfectBreakfast.Application/Repositories/IManagementUnitRepository.cs
src/PerfectBreakfast.Application/Repositories/ISupplierRepository.cs
src/PerfectBreakfast.Application/Repositories/ISupplyAssigmentRepository.cs
src/PerfectBreakfast.Application/Services/ManagementUnitService.cs
src/PerfectBreakfast.Application/Services/SupplierService.cs
src/PerfectBreakfast.Application/Services/SupplyAssigmentService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Mappers/MapsterConfig.cs
src/PerfectBreakfast.Infrastructure/Repositories/ManagementUnitRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplyAssigmentRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

Creat supply asigment

---

src/PerfectBreakfast.API/Controllers/V1/DeliveryUnitController.cs
src/PerfectBreakfast.API/Controllers/V1/ManagementUnitController.cs
src/PerfectBreakfast.Application/Interfaces/IDeliveryUnitService.cs
src/PerfectBreakfast.Application/Interfaces/IManagementUnitService.cs
src/PerfectBreakfast.Application/Services/DeliveryUnitService.cs
src/PerfectBreakfast.Application/Services/ManagementUnitService.cs

done paging

---

src/PerfectBreakfast.API/Controllers/V1/ComboController.cs
src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Controllers/V1/MenuController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/IComboService.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IFoodService.cs
src/PerfectBreakfast.Application/Interfaces/IMenuService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/DaliyOrder/Response/DailyOrderForManagemtUnitResponse.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/TotalFoodResponse.cs
src/PerfectBreakfast.Application/Repositories/ICompanyRepository.cs
src/PerfectBreakfast.Application/Services/ComboService.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/ManagementUnitService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/CompanyRepository.cs

Update combo và menu 
GetTotalFoodByManagementUnit
GetDailyOrderByCompanyInDayForMamnagementUnit
GetDetailDailyOrderByCompanyInDayForMamnagementUnit
Change name api in status

#71 feat/fix_combo_menu

---

src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitDTO.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitDetailResponse.cs
src/PerfectBreakfast.Application/Models/ManagementUnitModels/Resposne/ManagementUnitResponseModel.cs
src/PerfectBreakfast.Application/Services/ManagementUnitService.cs

fix name managementUnit

---

src/PerfectBreakfast.API/Validations/Combo/UpdateComboValidator.cs
src/PerfectBreakfast.API/Validations/Company/UpdateCompanyValidator.cs
src/PerfectBreakfast.API/Validations/Food/FoodValidator.cs
src/PerfectBreakfast.API/Validations/Food/UpdateFoodValidator.cs
src/PerfectBreakfast.API/Validations/Menu/UpdateMenuValidator.cs

Validate combo, menu, food, company

Validate combo, menu, food, company

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/DaliyOrder/Response/DailyOrderForManagemtUnitResponse.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/FoodAssignmentResponse.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/SupplierFoodAssignmentResponse.cs
src/PerfectBreakfast.Application/Repositories/IManagementUnitRepository.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Domain/Enums/DailyOrderStatus.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Repositories/ManagementUnitRepository.cs

paging dailyorder, add status, get by managementUnit

Feat/update daily order, food assignment

---

src/PerfectBreakfast.API/Controllers/V1/SupplierCommissionRateController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierCommissionRateService.cs
src/PerfectBreakfast.Application/Models/SupplierCommissionRate/Respone/SupplierMoreFoodRespone.cs
src/PerfectBreakfast.Application/Repositories/ISupplierCommissionRateRepository.cs
src/PerfectBreakfast.Application/Services/SupplierCommissionRateService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierCommissionRateRepository.cs

Getfoodbysupplier

---

src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/SupplierFoodAssignmentForSupplier.cs

Add folder

---

src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/FoodAssignmentResponse.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/SupplierFoodAssignmentForSupplier.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/SupplierFoodAssignmetForPartner.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs

Update createSupplierFoodAssignment, GetSupplierFoodAssignment by Partner and Supplier Group by DateCooked

Update createSupplierFoodAssignment, GetSupplierFoodAssignment 

---

src/PerfectBreakfast.Application/Models/OrderModel/Response/OrderDetailResponse.cs
src/PerfectBreakfast.Application/Services/OrderService.cs

Update order detail

---

src/PerfectBreakfast.API/Controllers/V1/SupplierController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierService.cs
src/PerfectBreakfast.Application/Repositories/IUserRepository.cs
src/PerfectBreakfast.Application/Services/SupplierService.cs
src/PerfectBreakfast.Infrastructure/Repositories/UserRepository.cs

getSupplierByPartner

---

src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.API/Validations/SupplierFoodAssignment/SupplierFoodAssignmentValidator.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Request/SupplierFoodAssignmentRequest.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Request/SupplierFoodsAssignmentRequest.cs
src/PerfectBreakfast.Application/Services/OrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs

Fix supplier food assignment

---

src/PerfectBreakfast.API/Controllers/V1/UserController.cs
src/PerfectBreakfast.Application/Interfaces/IShippingOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IUnitOfWork.cs
src/PerfectBreakfast.Application/Interfaces/IUserService.cs
src/PerfectBreakfast.Application/Models/ShippingOrder/Request/CreateShippingOrderRequest.cs
src/PerfectBreakfast.Application/Models/ShippingOrder/Response/ShippingOrderRespone.cs
src/PerfectBreakfast.Application/Repositories/IShippingOrderRepository.cs
src/PerfectBreakfast.Application/Repositories/IUserRepository.cs
src/PerfectBreakfast.Application/Services/ShippingOrderService.cs
src/PerfectBreakfast.Application/Services/UserService.cs
src/PerfectBreakfast.Infrastructure/DenpendencyInjection.cs
src/PerfectBreakfast.Infrastructure/Repositories/ShippingOrderRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/UserRepository.cs
src/PerfectBreakfast.Infrastructure/UnitOfWork.cs

getDeliveryStaffByDeliveryAdmin

getDeliveryStaffByDeliveryAdmin

---

src/PerfectBreakfast.API/Controllers/V1/ShippingOrderController.cs
src/PerfectBreakfast.Application/Services/UserService.cs

Dayli order get delivery staff

---

src/PerfectBreakfast.API/Controllers/V1/ComboController.cs
src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Controllers/V1/MenuController.cs
src/PerfectBreakfast.API/Controllers/V1/OrderController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.API/Validations/Company/CompanyValidator.cs
src/PerfectBreakfast.Application/Interfaces/ICompanyService.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/ComboService.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Application/Services/OrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Domain/Entities/Category.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Migrations/AppDbContextModelSnapshot.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

Fix auto create daily order, authorized, comment in controller

Fix auto create daily order, authorized, comment in controller

---

src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Services/FoodService.cs

fix supplier authen

---

src/PerfectBreakfast.Application/Services/ShippingOrderService.cs
src/PerfectBreakfast.Domain/Enums/ShippingStatus.cs

update status shipping order

---

src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

Fix auto create daily order

---

src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Infrastructure/Repositories/PartnerRepository.cs

Fix get food for partner

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs

Add authen

---

src/PerfectBreakfast.Application/Models/PartnerModels/Response/PartnerDetailResponse.cs
src/PerfectBreakfast.Application/Services/PartnerService.cs
src/PerfectBreakfast.Infrastructure/Repositories/PartnerRepository.cs

fix partner detail

---

src/PerfectBreakfast.Infrastructure/Repositories/CompanyRepository.cs

fix company repo

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Validations/DailyOrder/DailyOrderValidator.cs
src/PerfectBreakfast.API/Validations/DailyOrder/UpdateDailyOrderValidatorcs.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Response/CompanyForDailyOrderResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Request/DailyOrderRequest.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Request/UpdateDailyOrder.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Request/UpdateDailyOrderRequest.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderForDeliveryResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderForPartnerResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderModelResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderResponseExcel.cs
src/PerfectBreakfast.Application/Models/ShippingOrder/Response/ShippingOrderHistoryForShipperResponse.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Mappers/MapsterConfig.cs

Fix daily order name folder, get daily order by partner

Fix daily order name folder, get daily order by partner

---

src/PerfectBreakfast.Application/Services/MenuService.cs

fix delete menu

---

src/PerfectBreakfast.Application/Interfaces/IFoodService.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/TotalFoodForPartnerResponse.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs

fix get daily order by partner

fix get daily order by partner

---

src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierController.cs
src/PerfectBreakfast.Application/Interfaces/IFoodService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierService.cs
src/PerfectBreakfast.Application/Repositories/IDeliveryRepository.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/SupplierService.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DeliveryRepository.cs

fix update company, get supplier by partner

fix update company, get supplier by partner

---

src/PerfectBreakfast.API/Controllers/V1/ShippingOrderController.cs
src/PerfectBreakfast.Application/Interfaces/IShippingOrderService.cs
src/PerfectBreakfast.Application/Models/ShippingOrder/Response/ShippingOrderDTO.cs
src/PerfectBreakfast.Application/Repositories/IShippingOrderRepository.cs
src/PerfectBreakfast.Application/Services/ShippingOrderService.cs
src/PerfectBreakfast.Infrastructure/Repositories/ShippingOrderRepository.cs

Get more shipper

---

src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Request/UpdateSupplierFoodAssignment.cs
src/PerfectBreakfast.Application/Repositories/ISupplierFoodAssignmentRepository.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierFoodAssignmentRepository.cs

fix status

---

src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/MenuService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

fix get menu by date, fix get daily order by admin

fix get menu by date, fix get daily order by admin

---

src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/FoodAssignmentGroupByPartner.cs
src/PerfectBreakfast.Application/Repositories/ISupplierFoodAssignmentRepository.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierFoodAssignmentRepository.cs

feat download excel

---

src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/SupplierService.cs

fix search

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/UserService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

fix daily order status and forget password

fix daily order status and forget password

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Controllers/V1/ShippingOrderController.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IShippingOrderService.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/TotalFoodForCompanyResponse.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/ShippingOrderService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/ShippingOrderRepository.cs

fix daily order status,

---

src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs

fix get daily order

---

src/PerfectBreakfast.API/Controllers/V1/ShippingOrderController.cs
src/PerfectBreakfast.Application/Services/ShippingOrderService.cs

fix permission

---

src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/BackgroundJobServices/ManagementService.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierRepository.cs

feat send email to supplier and partner

feat send email to supplier and partner

---

src/PerfectBreakfast.Application/Interfaces/IShippingOrderService.cs
src/PerfectBreakfast.Application/Models/FoodModels/Response/TotalComboForStaff.cs
src/PerfectBreakfast.Application/Services/ShippingOrderService.cs

Fix staff get daily order

---

src/PerfectBreakfast.API/Controllers/V1/CompanyController.cs
src/PerfectBreakfast.Application/Interfaces/ICompanyService.cs
src/PerfectBreakfast.Application/Repositories/ICompanyRepository.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/Repositories/CompanyRepository.cs

feat search company

---

src/PerfectBreakfast.API/Controllers/V1/ComboController.cs
src/PerfectBreakfast.API/Controllers/V1/FoodController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.API/Validations/Food/FoodValidator.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IExportExcelService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/CreateFoodRequestModels.cs
src/PerfectBreakfast.Application/Models/FoodModels/Request/UpdateFoodRequestModels.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/FoodService.cs
src/PerfectBreakfast.Application/Services/OrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Infrastructure/ExportService/ExportExcelService.cs

Fix create food and update food

Fix create food and update food

---

src/PerfectBreakfast.Application/Models/MenuModels/Response/MenuIsSelectedResponse.cs
src/PerfectBreakfast.Application/Services/MenuService.cs

fix get menu selected

---

src/PerfectBreakfast.Application/Models/MenuModels/Response/MenuResponse.cs
src/PerfectBreakfast.Application/Services/MenuService.cs

fix get menu

---

src/PerfectBreakfast.Application/Services/ComboService.cs

fix get all combo

---

src/PerfectBreakfast.API/Validations/Order/OrderDetailValidator.cs

fix order detail validator

---

src/PerfectBreakfast.API/Controllers/V1/DailyOrderController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierController.cs
src/PerfectBreakfast.API/Controllers/V1/SupplierFoodAssignmentController.cs
src/PerfectBreakfast.Application/Interfaces/IDailyOrderService.cs
src/PerfectBreakfast.Application/Interfaces/IExportExcelService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Interfaces/ISupplierService.cs
src/PerfectBreakfast.Application/Models/CompanyModels/Response/CompanyForDailyOrderResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/Response/DailyOrderForPartnerResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/StatisticResponse/CompanyForDailyOrder.cs
src/PerfectBreakfast.Application/Models/DailyOrder/StatisticResponse/DailyOrderStatisticResponse.cs
src/PerfectBreakfast.Application/Models/DailyOrder/StatisticResponse/FoodForDailyOrder.cs
src/PerfectBreakfast.Application/Models/DailyOrder/StatisticResponse/MealForDailyOrder.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/FoodAssignmentResponse.cs
src/PerfectBreakfast.Application/Models/SupplierFoodAssignmentModels/Response/SupplierFoodAssignmentForSuperAdmin.cs
src/PerfectBreakfast.Application/Repositories/IDailyOrderRepository.cs
src/PerfectBreakfast.Application/Repositories/ISupplierFoodAssignmentRepository.cs
src/PerfectBreakfast.Application/Services/CompanyService.cs
src/PerfectBreakfast.Application/Services/DailyOrderService.cs
src/PerfectBreakfast.Application/Services/MealService.cs
src/PerfectBreakfast.Application/Services/OrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs
src/PerfectBreakfast.Application/Services/SupplierService.cs
src/PerfectBreakfast.Infrastructure/ExportService/ExportExcelService.cs
src/PerfectBreakfast.Infrastructure/Mappers/MapsterConfig.cs
src/PerfectBreakfast.Infrastructure/Repositories/CompanyRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/DailyOrderRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierFoodAssignmentRepository.cs
src/PerfectBreakfast.Infrastructure/Repositories/SupplierRepository.cs

Fix company, supplier, food. Add Statistic for daily order

Fix company, supplier, food. Add Statistic for daily order

---

src/PerfectBreakfast.Application/Services/ShippingOrderService.cs
src/PerfectBreakfast.Application/Services/SupplierFoodAssignmentService.cs

fix supplier assign complete
